apps:
  arch:
    - bitwarden
    - dbeaver
    - vivaldi
    - vivaldi-ffmpeg-codecs
  aur:
    - brave-bin
    - bruno-bin
    - redisinsight-bin
  remove:
    - chromium
    - libreoffice-fresh
    - tmux
    - foot
webapps:
  remove:
    - Discord
    - Google Contacts
    - Google Maps
    - Google Messages
    - Google Photos
    - HEY
    - X
    - YouTube
    - Zoom
