apps:
  arch:
    - rustdesk
    - foot
    - fish
    - xournalpp
  aur:
    - bruno-bin
    - helium-browser-bin
    - redisinsight-bin
    - termius
  remove:
    - bitwarden
    - dbeaver
    - chromium
    - libreoffice-fresh
    - tmux
    - ghostty
    - pinta
    - omawrite
    - omacalc
    - omacut
    - tensaku
    - kdenlive
    - cliamp
    - moonlight-qt
    - system-config-printer
    - grim
    - slurp
webapps:
  remove:
    - Basecamp
    - Discord
    - Google Contacts
    - Google Maps
    - Google Messages
    - Google Photos
    - HEY
    - X
    - YouTube
    - Zoom
