apps:
  arch:
    - bitwarden
  aur:
    - brave-bin
  remove:
    - chromium
    - libreoffice-fresh
webapps:
  remove:
    - Discord
    - Google Contacts
    - Google Maps
    - Google Messages
    - Google Photos
    - HEY
    - X
    - YouTube
    - Zoom
