[metadata]
name = "Homunculus"
author = "Fahmi Aulia Rahman"

[colors]
foreground = "#FFF9F3"
background = "#050505"
cursor_bg = "#FFF9F3"
cursor_border = "#FFF9F3"
cursor_fg = "#050505"
compose_cursor = "#C95448"
selection_bg = "#4A1C17"
selection_fg = "#FFF9F3"
scrollbar_thumb = "#321B17"
split = "#321B17"
visual_bell = "#C95448"
ansi = [
  "#050505",
  "#C95448",
  "#91A96F",
  "#D9B165",
  "#7FA7C0",
  "#B496C6",
  "#78B6AD",
  "#E7DFD8",
]
brights = [
  "#25201E",
  "#E8796B",
  "#B4C98E",
  "#F0CA7C",
  "#9BC3DC",
  "#D0B3E0",
  "#9AD2C8",
  "#FFF9F3",
]

[colors.indexed]
16 = "#D98A5B"
17 = "#831F15"
